services:
  db:
    image: postgres:15.3
    restart: always
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    image: gabo71096/rails_api:1.0
    restart: always
    build:
      context: ./api
      args:
        RAILS_ENV: development
        RAILS_SERVE_STATIC_FILES: false
        RAILS_LOG_TO_STDOUT: false
        BUNDLE_WITHOUT:
    depends_on:
      - db
    volumes:
      - ./api:/api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 'api'"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  client:
    image: gabo71096/react_client:1.0
    restart: always
    build: ./client
    depends_on:
      - api
    ports:
      - 5173:5173
    volumes:
      - ./client:/client
